- hosts: minipc2
  become: yes
  vars:
    repo_url: https://github.com/eknath-techo/kafka_setup.git
    user: "tech"
    repo_location: "/home/{{ user  }}/kafka_setup"
    venv_location: "{{ repo_location }}/venv"
    supervisor_conf_file: producer.conf
  tasks:
    - name: Print HOME environment variable
      debug:
        msg: "Home directory is {{ repo_location }}"

    - name: Clone project code.
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_location }}"
        update: yes

    - name: Set 777 permissions for all files in the cloned directory.
      file:
        path: "{{ repo_location }}"
        state: directory
        recurse: yes
        mode: '0777'

    - name: installing packages for python env
      apt:
        name: 
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - python3-venv
        update_cache: yes

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv "{{ venv_location }}"
   
    - name: Install requirements
      pip: 
        requirements: "{{ repo_location }}/requirements.txt"
        virtualenv: "{{ venv_location }}"
        virtualenv_python: python3

    - name: Install supervisord
      apt:
        name: supervisor
        state: present
        update_cache: yes

    - name: Create Supervisor configuration directory
      file:
        path: /etc/supervisor/conf.d/
        state: directory
        mode: '0755'

    - name: Copy Supervisor configuration file for test.py
      copy:
            src: "files/{{ supervisor_conf_file }}"
            dest: "/etc/supervisor/conf.d/{{ supervisor_conf_file }}"
            mode: '0644'

    - name: Reload Supervisor to apply new configuration
      command: supervisorctl reread

    - name: Update Supervisor with new configuration
      command: supervisorctl update

    - name: Ensure Supervisor is running
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: Start producer.py using Supervisor
      command: supervisorctl start producer_from_local
